development:
  adapter: async


test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:43ff0aeb32161fd6d2a02e410bd20a56@tarpon.redistogo.com:9037/
  channel_prefix: message_me_production
